@serverLocal = http://localhost:4004
@serverViaAPPROUTER = http://localhost:5000

@serverDEV = https://loro-piana-s-p-a--btp-development-loro-piana-82xq0cpc-d7b0726e1.cfapps.eu30.hana.ondemand.com
@tokenUrl = https://btp-development-loro-piana-82xq0cpc.authentication.eu30.hana.ondemand.com/oauth/token
@serverViaDEST = https://btp-development-loro-piana-82xq0cpc.launchpad.cfapps.eu30.hana.ondemand.com/dynamic_dest/S4HANA/sap/opu/odata/sap/ZZ1_I_SHIPPINGPOINT_CDS/$metadata
### ------------------------------------------------------------------------
# GET TOKEN - GET
# @name getToken
GET {{tokenUrl}}/?grant_type=client_credentials&response_type=token
Authorization: Basic c2ItenN1YmNvbnRyYWN0aW5nX2NvY2twaXQtYXV0aC1zcnYhdDIxNjkyOjMyM2Y4MmI1LTEzOGYtNGE3Ny1hZmQ5LWQ5NTkwODBmNWNlMCRRbWtYY0xwdk1kRzU2OHZXRloyc2QxXzFMa2VvM3lhaTFhY21oTk5ESlFBPQ==

###
@tokenValue = {{getToken.response.body.access_token}}

### ------------------------------------------------------------------------
# TEST SERVER DEV
# Authorization: Bearer {{tokenValue}} (sotto content type)
POST {{serverDEV}}/odata/v4/criftool/getUserInfo
Authorization: Bearer {{tokenValue}} 
Content-Type: application/json

{
    "ID" : "123"
}

### ------------------------------------------------------------------------
# TEST SERVER DEV 
# Authorization: Bearer {{tokenValue}} (sotto content type)
GET {{serverDEV}}/odata/v4/catalog/$metadata?sap-language=IT
Authorization: Bearer {{tokenValue}}

### ------------------------------------------------------------------------
# TEST SERVER DEV 
# Authorization: Bearer {{tokenValue}} (sotto content type)
GET {{serverDEV}}/odata/v4/catalog/ZZ1_I_ShippingPoint
Authorization: Bearer {{tokenValue}}

### ------------------------------------------------------------------------
# TEST SERVER DEV 
# Authorization: Bearer {{tokenValue}} (sotto content type)
GET {{serverDEV}}/odata/v4/catalog/ZZ1_I_UNION_SUBCONCTR_COMP
Authorization: Bearer {{tokenValue}}

